"""Load db_export/mongodb/collections/*.json into MongoDB. Idempotent.

Generated by build_migrations.py. Do not edit by hand.

Every document carries a stable _id derived from its natural key, so this is
an upsert rather than an insert: running it twice changes nothing the second
time.

Dates arrive as MongoDB Extended JSON ({"$date": ...}) and land as real BSON
dates, so a range query on a date is a date comparison rather than a string
one.

Usage:
    python3 load_data.py --uri "mongodb+srv://..." --db ai_brain
    python3 load_data.py --uri ... --db ai_brain --dry-run
    python3 load_data.py --uri ... --db ai_brain --only source_documents
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

COLLECTIONS = Path(__file__).resolve().parent.parent / "collections"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--uri", required=True)
    ap.add_argument("--db", required=True)
    ap.add_argument("--only", action="append", default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    files = sorted(COLLECTIONS.glob("*.json"))
    if args.only:
        wanted = set(args.only)
        files = [f for f in files if f.stem in wanted]
        missing = wanted - {f.stem for f in files}
        if missing:
            print(f"no such collection: {sorted(missing)}", file=sys.stderr)
            return 2
    if not files:
        print(f"nothing to load from {COLLECTIONS}", file=sys.stderr)
        return 2

    if args.dry_run:
        total = 0
        for f in files:
            docs = json.loads(f.read_text(encoding="utf-8"))
            total += len(docs)
            roles = sorted({r for d in docs for r in d.get("allowed_roles", [])})
            print(f"  {f.stem:32} {len(docs):>6,} docs   roles: {','.join(roles)}")
        print(f"\n  {len(files)} collections, {total:,} documents "
              "(dry run, nothing written)")
        return 0

    try:
        from pymongo import MongoClient, UpdateOne
        from bson import json_util
    except ImportError:
        print("pip install pymongo", file=sys.stderr)
        return 2

    db = MongoClient(args.uri)[args.db]
    total = 0
    for f in files:
        # json_util turns {"$date": ...} into a real datetime on the way in.
        docs = json_util.loads(f.read_text(encoding="utf-8"))
        if not docs:
            print(f"  {f.stem:32} empty, skipped")
            continue
        ids = [d["_id"] for d in docs]
        if len(set(ids)) != len(ids):
            print(f"  {f.stem}: duplicate _id, refusing to load", file=sys.stderr)
            return 1
        ops = [UpdateOne({"_id": d["_id"]}, {"$set": d}, upsert=True) for d in docs]
        res = db[f.stem].bulk_write(ops, ordered=False)
        total += len(docs)
        print(f"  {f.stem:32} {len(docs):>6,} docs  "
              f"({res.upserted_count} new, {res.modified_count} updated)")
    print(f"\n  {len(files)} collections, {total:,} documents into {args.db}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
