-- Generated 2026-09-13 13:21 UTC by build_migrations.py from db_export/schema.json
-- Do not edit by hand; re-run the generator instead.
-- Requires PostgreSQL 15+ (security_invoker views).

-- Every table carries its own permission scope in allowed_roles.
-- 003_enable_rls.sql is what turns that column into a boundary.

CREATE TABLE IF NOT EXISTS _migrations (
    name        TEXT PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Deal Portfolio: 256 rows
CREATE TABLE deal_portfolio (
    row_key                        TEXT PRIMARY KEY,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    property_city                  TEXT,
    property_state                 TEXT,
    property_zip                   TEXT,
    property_county                TEXT,
    property_location_source       TEXT NOT NULL,
    deal_status                    TEXT NOT NULL,
    exit_strategy                  TEXT,
    deal_source                    TEXT,
    sold_year                      INTEGER,
    sold_date                      DATE,
    sold_date_source               TEXT,
    purchase_price                 NUMERIC(14,2),
    purchase_date                  DATE,
    sale_price                     NUMERIC(14,2),
    contractor                     TEXT,
    contractor_crew                TEXT,
    house_type                     TEXT,
    house_style                    TEXT,
    beds                           INTEGER,
    baths_full                     INTEGER,
    baths_half                     INTEGER,
    sqft_above_grade               INTEGER,
    sqft_total_finished            INTEGER,
    sqft_below_grade_fin           INTEGER,
    sqft_below_grade_unfin         INTEGER,
    sqft_below_grade_total         INTEGER,
    mls_list_date                  DATE,
    year_built                     INTEGER,
    yr_major_reno                  INTEGER,
    start_date                     DATE,
    completion_date                DATE,
    mls_number                     TEXT,
    mls_status                     TEXT,
    mls_list_price                 INTEGER,
    mls_original_price             INTEGER,
    mls_close_price                INTEGER,
    mls_close_date                 DATE,
    mls_dom                        INTEGER,
    mls_cdom                       INTEGER,
    buyer_financing                TEXT,
    school_district                TEXT,
    subdivision                    TEXT,
    hud_purchase_file_no           TEXT,
    hud_sale_file_no               TEXT,
    hud_settlement_dates           TEXT,
    lenders                        TEXT,
    loan_count                     INTEGER NOT NULL,
    hud_count                      INTEGER NOT NULL,
    sources_present                TEXT NOT NULL,
    source_count                   INTEGER NOT NULL,
    purchase_date_source           TEXT,
    county_code                    TEXT,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_deal_portfolio_property_key UNIQUE (property_key),
    CONSTRAINT ck_deal_portfolio_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_deal_portfolio_roles CHECK (array_length(allowed_roles, 1) >= 1)
);

-- Deal Aggregates: 200 rows
CREATE TABLE deal_aggregates (
    row_key                        TEXT PRIMARY KEY,
    aggregate_id                   INTEGER NOT NULL,
    sheet                          TEXT NOT NULL,
    exit_strategy                  TEXT NOT NULL,
    deal_source                    TEXT NOT NULL,
    label                          TEXT NOT NULL,
    metric_value                   NUMERIC(14,2),
    sold_year                      INTEGER,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_deal_aggregates_aggregate_id UNIQUE (aggregate_id),
    CONSTRAINT ck_deal_aggregates_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_deal_aggregates_roles CHECK (array_length(allowed_roles, 1) >= 1)
);

-- Deal Portfolio: 256 rows
CREATE TABLE deal_economics (
    row_key                        TEXT PRIMARY KEY,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    profit                         NUMERIC(14,2),
    profit_source                  TEXT,
    gross_margin                   NUMERIC(14,2),
    total_cash_in                  NUMERIC(14,2),
    total_cash_in_deal             NUMERIC(14,2),
    arv                            INTEGER,
    budget_total                   NUMERIC(14,2),
    budget_total_labor             NUMERIC(14,2),
    budget_total_materials         NUMERIC(14,2),
    actual_total_rehab             NUMERIC(14,2),
    actual_rehab_labor             NUMERIC(14,2),
    actual_rehab_materials         NUMERIC(14,2),
    closing_costs_buyer            NUMERIC(14,2),
    closing_costs_seller           NUMERIC(14,2),
    total_holding_costs            NUMERIC(14,2),
    top_20_flag                    TEXT,
    deal_rank                      INTEGER,
    profit_ballpark                TEXT,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_deal_economics_property_key UNIQUE (property_key),
    CONSTRAINT ck_deal_economics_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_deal_economics_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_deal_economics_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Focus & Avoid: 15 rows
CREATE TABLE focus_and_avoid (
    row_key                        TEXT PRIMARY KEY,
    segment                        TEXT NOT NULL,
    segment_rank                   INTEGER NOT NULL,
    focus                          TEXT NOT NULL,
    focus_expanded                 TEXT NOT NULL,
    deals                          INTEGER NOT NULL,
    total_profit                   NUMERIC(14,2) NOT NULL,
    avg_profit                     NUMERIC(14,2) NOT NULL,
    median_profit                  INTEGER NOT NULL,
    top_20_hit_rate                NUMERIC(14,2) NOT NULL,
    why_it_matters                 TEXT NOT NULL,
    confidence                     TEXT NOT NULL,
    recommended_action             TEXT NOT NULL,
    confidence_basis               TEXT NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT ck_focus_and_avoid_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_focus_and_avoid_roles CHECK (array_length(allowed_roles, 1) >= 1)
);

-- HUD Settlements: 382 rows
CREATE TABLE hud_settlements (
    row_key                        TEXT PRIMARY KEY,
    source_file                    TEXT NOT NULL,
    doc_format                     TEXT NOT NULL,
    exit_strategy                  TEXT NOT NULL,
    transaction_type               TEXT NOT NULL,
    file_number                    TEXT,
    settlement_date                DATE,
    buyer_name                     TEXT,
    seller_name                    TEXT,
    lender_name                    TEXT,
    property_key                   TEXT,
    canonical_address              TEXT,
    property_street                TEXT,
    property_city                  TEXT,
    property_state                 TEXT,
    property_zip                   TEXT,
    contract_price                 TEXT,
    loan_amount                    NUMERIC(14,2),
    earnest_deposit                NUMERIC(14,2),
    gross_due_from_borrower        NUMERIC(14,2),
    gross_due_to_seller            NUMERIC(14,2),
    cash_from_borrower             NUMERIC(14,2),
    cash_to_seller                 NUMERIC(14,2),
    closing_group                  TEXT NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_hud_settlements_source_file UNIQUE (source_file),
    CONSTRAINT ck_hud_settlements_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_hud_settlements_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_hud_settlements_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Loan Activity: 277 rows
CREATE TABLE loan_activity (
    row_key                        TEXT PRIMARY KEY,
    activity_id                    INTEGER NOT NULL,
    lender                         TEXT NOT NULL,
    source_file                    TEXT NOT NULL,
    loan_or_account_number         TEXT,
    activity_date                  DATE NOT NULL,
    activity_type                  TEXT NOT NULL,
    description                    TEXT NOT NULL,
    interest                       NUMERIC(14,2),
    principal                      INTEGER,
    fees                           INTEGER,
    amount                         NUMERIC(14,2) NOT NULL,
    balance_after                  INTEGER,
    is_mezzanine                   TEXT,
    per_diem_rate                  NUMERIC(14,2),
    amounts_raw                    TEXT,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    is_reversal                    TEXT NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_loan_activity_activity_id UNIQUE (activity_id),
    CONSTRAINT ck_loan_activity_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_loan_activity_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_loan_activity_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Loan Statements: 143 rows
CREATE TABLE loan_statements (
    row_key                        TEXT PRIMARY KEY,
    source_file                    TEXT NOT NULL,
    lender                         TEXT NOT NULL,
    doc_format                     TEXT NOT NULL,
    loan_or_account_number         TEXT,
    borrower_name                  TEXT,
    property_key                   TEXT,
    canonical_address              TEXT,
    property_city                  TEXT,
    property_state                 TEXT,
    property_zip                   TEXT,
    statement_date                 DATE NOT NULL,
    maturity_date                  DATE,
    interest_rate_pct              NUMERIC(14,2),
    principal_balance              INTEGER NOT NULL,
    payment_amount                 NUMERIC(14,2),
    next_payment_date              DATE,
    undrawn_amount                 INTEGER,
    remaining_interest             INTEGER,
    past_due_principal             INTEGER,
    past_due_interest              NUMERIC(14,2),
    past_due_advances              INTEGER,
    past_due_fees                  INTEGER,
    past_due_total                 NUMERIC(14,2),
    payment_period                 TEXT,
    principal_period               INTEGER,
    principal_ytd                  INTEGER,
    principal_lifetime             INTEGER,
    interest_period                NUMERIC(14,2),
    interest_ytd                   NUMERIC(14,2),
    interest_lifetime              NUMERIC(14,2),
    fees_period                    INTEGER,
    fees_ytd                       INTEGER,
    fees_lifetime                  INTEGER,
    statement_format               TEXT,
    due_date                       DATE,
    close_date                     DATE,
    disbursed_principal_balance    INTEGER,
    remaining_construction_funds   INTEGER,
    escrow_balance                 INTEGER,
    other_fees_due                 INTEGER,
    past_due_amount                INTEGER,
    amount_already_paid            INTEGER,
    late_fee_amount                NUMERIC(14,2),
    loan_officer                   TEXT,
    summary_year                   INTEGER,
    origination_date               DATE,
    interest_paid_ytd              NUMERIC(14,2),
    beginning_principal_balance    INTEGER,
    real_estate_taxes_paid         INTEGER,
    ending_principal_balance       INTEGER,
    insurance_paid                 INTEGER,
    reserve_balance                NUMERIC(14,2),
    impound_balance                INTEGER,
    payment_due_date               DATE,
    unpaid_interest                INTEGER,
    unpaid_charges                 INTEGER,
    late_charges_due               INTEGER,
    statement_entity               TEXT,
    account_current_balance        NUMERIC(14,2),
    property_count                 INTEGER,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_loan_statements_source_file UNIQUE (source_file),
    CONSTRAINT ck_loan_statements_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_loan_statements_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_loan_statements_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Master Budget: 46 rows
CREATE TABLE master_budget (
    row_key                        TEXT PRIMARY KEY,
    source_file                    TEXT NOT NULL,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    lockbox                        TEXT NOT NULL,
    arv                            INTEGER,
    contractor                     TEXT,
    project_timeline               TEXT,
    start_date                     DATE NOT NULL,
    completion_date                DATE NOT NULL,
    construction_date_source       TEXT NOT NULL,
    layout_summary                 TEXT,
    house_type                     TEXT,
    house_type_source              TEXT,
    house_style                    TEXT,
    house_style_source             TEXT,
    total_labor                    NUMERIC(14,2) NOT NULL,
    total_materials                NUMERIC(14,2) NOT NULL,
    total_budget                   NUMERIC(14,2) NOT NULL,
    agreed_labor_budget            INTEGER,
    home_depot_materials_total     NUMERIC(14,2) NOT NULL,
    amazon_materials_total         NUMERIC(14,2) NOT NULL,
    other_materials_total          NUMERIC(14,2) NOT NULL,
    labor_budget_total             NUMERIC(14,2),
    other_labor_total              NUMERIC(14,2),
    construction_start_proxy       DATE,
    property_county                TEXT NOT NULL,
    property_county_source         TEXT NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_master_budget_source_file UNIQUE (source_file),
    CONSTRAINT ck_master_budget_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_master_budget_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_master_budget_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Master Budget Line Items: 3,374 rows
CREATE TABLE master_budget_line_items (
    row_key                        TEXT PRIMARY KEY,
    line_item_id                   INTEGER NOT NULL,
    source_file                    TEXT NOT NULL,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    budget_section                 TEXT NOT NULL,
    description                    TEXT,
    amount                         NUMERIC(14,2) NOT NULL,
    line_item_date                 DATE,
    method_or_note                 TEXT,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_master_budget_line_items_line_item_id UNIQUE (line_item_id),
    CONSTRAINT ck_master_budget_line_items_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_master_budget_line_items_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_master_budget_line_items_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- MLS Listings: 116 rows
CREATE TABLE mls_listings (
    row_key                        TEXT PRIMARY KEY,
    source_file                    TEXT NOT NULL,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    listing_status                 TEXT NOT NULL,
    status_date                    DATE,
    close_price_header             INTEGER NOT NULL,
    mls_number                     TEXT NOT NULL,
    tax_id                         TEXT NOT NULL,
    structure_type_raw             TEXT NOT NULL,
    style_raw                      TEXT NOT NULL,
    house_type                     TEXT NOT NULL,
    house_style                    TEXT NOT NULL,
    beds                           INTEGER NOT NULL,
    baths_full                     INTEGER NOT NULL,
    baths_half                     INTEGER,
    total_rooms                    INTEGER,
    levels                         INTEGER NOT NULL,
    year_built                     INTEGER NOT NULL,
    sqft_above_grade               INTEGER NOT NULL,
    sqft_below_grade_fin           INTEGER,
    sqft_below_grade_unfin         INTEGER,
    sqft_below_grade_total         INTEGER,
    sqft_total_finished            INTEGER NOT NULL,
    sqft_total                     INTEGER NOT NULL,
    price_per_sqft                 NUMERIC(14,2) NOT NULL,
    lot_acres                      NUMERIC(14,2),
    lot_sqft                       INTEGER,
    property_county                TEXT NOT NULL,
    school_district                TEXT NOT NULL,
    subdivision                    TEXT NOT NULL,
    waterfront                     TEXT NOT NULL,
    garage                         TEXT NOT NULL,
    central_air                    TEXT NOT NULL,
    basement                       TEXT NOT NULL,
    original_price                 INTEGER NOT NULL,
    previous_list_price            INTEGER,
    last_list_price                INTEGER,
    close_price                    INTEGER,
    dom                            INTEGER NOT NULL,
    cdom                           INTEGER NOT NULL,
    agreement_of_sale_date         DATE,
    close_date                     DATE,
    close_sale_type                TEXT,
    buyer_financing                TEXT,
    owner_name                     TEXT,
    construction_materials         TEXT NOT NULL,
    property_condition             TEXT,
    yr_major_reno                  INTEGER,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_mls_listings_source_file UNIQUE (source_file),
    CONSTRAINT ck_mls_listings_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_mls_listings_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_mls_listings_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Perf by County: 12 rows
CREATE TABLE performance_by_county (
    row_key                        TEXT PRIMARY KEY,
    county_code                    TEXT,
    deals                          INTEGER NOT NULL,
    total_profit                   NUMERIC(14,2) NOT NULL,
    avg_profit                     NUMERIC(14,2) NOT NULL,
    median_profit                  INTEGER NOT NULL,
    top_20_deals                   INTEGER NOT NULL,
    top_20_hit_rate                NUMERIC(14,2) NOT NULL,
    profit_share                   NUMERIC(14,2) NOT NULL,
    county                         TEXT,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_performance_by_county_county_code UNIQUE (county_code),
    CONSTRAINT ck_performance_by_county_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_performance_by_county_roles CHECK (array_length(allowed_roles, 1) >= 1)
);

-- Perf by Exit Strategy: 4 rows
CREATE TABLE performance_by_exit_strategy (
    row_key                        TEXT PRIMARY KEY,
    exit_strategy                  TEXT NOT NULL,
    deals                          INTEGER NOT NULL,
    total_profit                   NUMERIC(14,2) NOT NULL,
    avg_profit                     NUMERIC(14,2) NOT NULL,
    median_profit                  INTEGER NOT NULL,
    top_20_deals                   INTEGER NOT NULL,
    top_20_hit_rate                NUMERIC(14,2) NOT NULL,
    profit_share                   NUMERIC(14,2) NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_performance_by_exit_strategy_exit_strategy UNIQUE (exit_strategy),
    CONSTRAINT ck_performance_by_exit_strategy_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_performance_by_exit_strategy_roles CHECK (array_length(allowed_roles, 1) >= 1)
);

-- Accounting Summary: 136 rows
CREATE TABLE profit_reconciliation (
    row_key                        TEXT PRIMARY KEY,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    property_county_source         TEXT,
    house_type_source              TEXT,
    house_style_source             TEXT,
    lockbox                        TEXT,
    profit_breakdown               NUMERIC(14,2),
    profit_quickbooks              NUMERIC(14,2),
    loan_draw_amount               INTEGER,
    sources_present                TEXT NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_profit_reconciliation_property_key UNIQUE (property_key),
    CONSTRAINT ck_profit_reconciliation_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_profit_reconciliation_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_profit_reconciliation_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Property Profit Breakdown: 29 rows
CREATE TABLE property_profit_breakdown (
    row_key                        TEXT PRIMARY KEY,
    source_file                    TEXT NOT NULL,
    property_key                   TEXT,
    canonical_address              TEXT,
    purchase_date                  DATE,
    sale_date                      DATE,
    lockbox                        TEXT,
    purchase_price                 NUMERIC(14,2),
    sale_price                     NUMERIC(14,2),
    cash_out                       NUMERIC(14,2),
    cash_in_short                  NUMERIC(14,2),
    total_cash_in                  NUMERIC(14,2),
    total_cash_from_sale           NUMERIC(14,2),
    cash_received                  NUMERIC(14,2),
    total_profit                   NUMERIC(14,2),
    profit                         NUMERIC(14,2),
    mel_profit                     NUMERIC(14,2),
    mason_profit                   NUMERIC(14,2),
    expenses_total                 NUMERIC(14,2),
    labor_total                    NUMERIC(14,2),
    loan_at_end_of_sale            NUMERIC(14,2),
    hd_roof_hvac_total             NUMERIC(14,2),
    amazon_total                   NUMERIC(14,2),
    other_materials_total          NUMERIC(14,2),
    hauling                        NUMERIC(14,2),
    survey                         INTEGER,
    staging_photos                 INTEGER,
    staging_extension              INTEGER,
    insurance                      INTEGER,
    bge                            NUMERIC(14,2),
    points                         NUMERIC(14,2),
    interest                       NUMERIC(14,2),
    dispositions                   INTEGER,
    sale_out                       NUMERIC(14,2),
    gross_margin                   NUMERIC(14,2),
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_property_profit_breakdown_source_file UNIQUE (source_file),
    CONSTRAINT ck_property_profit_breakdown_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_property_profit_breakdown_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_property_profit_breakdown_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- QuickBooks P&L: 28 rows
CREATE TABLE quickbooks_pl (
    row_key                        TEXT PRIMARY KEY,
    source_file                    TEXT NOT NULL,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    real_estate_proceeds           INTEGER NOT NULL,
    total_property_sales_income    INTEGER NOT NULL,
    closing_costs_buyer            NUMERIC(14,2),
    closing_costs_seller           NUMERIC(14,2) NOT NULL,
    original_costs                 INTEGER,
    rehab_labor                    NUMERIC(14,2) NOT NULL,
    rehab_materials                NUMERIC(14,2),
    total_rehab_costs              NUMERIC(14,2) NOT NULL,
    total_property_sales_expenses  NUMERIC(14,2) NOT NULL,
    gross_profit                   NUMERIC(14,2) NOT NULL,
    total_cogs                     NUMERIC(14,2) NOT NULL,
    total_operating_expenses       INTEGER,
    net_operating_income           NUMERIC(14,2) NOT NULL,
    net_income                     NUMERIC(14,2) NOT NULL,
    total_holding_costs            NUMERIC(14,2),
    hoa                            NUMERIC(14,2),
    insurance_expenses             NUMERIC(14,2),
    interest_expenses              NUMERIC(14,2),
    utilities_electricity          NUMERIC(14,2),
    utilities_water                NUMERIC(14,2),
    property_sales_margin          NUMERIC(14,2) NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_quickbooks_pl_source_file UNIQUE (source_file),
    CONSTRAINT ck_quickbooks_pl_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_quickbooks_pl_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_quickbooks_pl_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

-- Rentals Cash in Deal: 5 rows
CREATE TABLE rentals_cash_in_deal (
    row_key                        TEXT PRIMARY KEY,
    source_file                    TEXT NOT NULL,
    property_key                   TEXT NOT NULL,
    canonical_address              TEXT NOT NULL,
    purchase_date                  DATE NOT NULL,
    refinance_date                 DATE NOT NULL,
    lockbox                        TEXT NOT NULL,
    initial_cash_out               NUMERIC(14,2),
    initial_cash_in                NUMERIC(14,2) NOT NULL,
    cash_out_to_refinance          NUMERIC(14,2),
    cash_back_from_refinance       INTEGER,
    cash_from_sale                 INTEGER,
    cash_in_for_refinance          NUMERIC(14,2),
    purchase_price                 NUMERIC(14,2) NOT NULL,
    expenses_total                 NUMERIC(14,2) NOT NULL,
    labor_total                    NUMERIC(14,2) NOT NULL,
    loan_draw_amount               INTEGER NOT NULL,
    draw_deficit                   NUMERIC(14,2) NOT NULL,
    total_cash_in_deal             NUMERIC(14,2) NOT NULL,
    total_cash_in                  NUMERIC(14,2) NOT NULL,
    source_tab                     TEXT NOT NULL,
    source_row                     INTEGER NOT NULL,
    department                     TEXT NOT NULL,
    sensitivity                    TEXT NOT NULL,
    allowed_roles                  TEXT[] NOT NULL,
    CONSTRAINT uq_rentals_cash_in_deal_source_file UNIQUE (source_file),
    CONSTRAINT ck_rentals_cash_in_deal_sensitivity CHECK (sensitivity IN ('internal', 'confidential', 'restricted')),
    CONSTRAINT ck_rentals_cash_in_deal_roles CHECK (array_length(allowed_roles, 1) >= 1),
    CONSTRAINT fk_rentals_cash_in_deal_property FOREIGN KEY (property_key)
        REFERENCES deal_portfolio (property_key)
);

INSERT INTO _migrations (name) VALUES ('001_create_tables')
    ON CONFLICT (name) DO NOTHING;
