"""Load db_export/postgres/tables/*.json into PostgreSQL. Idempotent.

Generated by build_migrations.py. Do not edit by hand.

Connect as the owner role, which has BYPASSRLS - otherwise the row-level
security added by 003 hides the rows from the loader itself.

Every row carries a stable row_key derived from its natural key, so this is
an upsert: running it twice changes nothing the second time. That matters
because the workbook gets regenerated whenever Dave sends more data.

Usage:
    python3 load_data.py --dsn "postgresql://ai_brain_owner@host/ai_brain"
    python3 load_data.py --dsn ... --dry-run
    python3 load_data.py --dsn ... --only deal_portfolio
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

TABLES = Path(__file__).resolve().parent.parent / "tables"

# deal_portfolio first: everything else has a foreign key into it.
FIRST = "deal_portfolio"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dsn", required=True)
    ap.add_argument("--only", action="append", default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    files = sorted(TABLES.glob("*.json"),
                   key=lambda p: (p.stem != FIRST, p.stem))
    if args.only:
        wanted = set(args.only)
        files = [f for f in files if f.stem in wanted]
        missing = wanted - {f.stem for f in files}
        if missing:
            print(f"no such table: {sorted(missing)}", file=sys.stderr)
            return 2
    if not files:
        print(f"nothing to load from {TABLES}", file=sys.stderr)
        return 2

    if args.dry_run:
        total = 0
        for f in files:
            rows = json.loads(f.read_text(encoding="utf-8"))
            total += len(rows)
            roles = sorted({r for x in rows for r in x["allowed_roles"]})
            print(f"  {f.stem:32} {len(rows):>6,} rows   roles: {','.join(roles)}")
        print(f"\n  {len(files)} tables, {total:,} rows (dry run, nothing written)")
        return 0

    try:
        import psycopg
    except ImportError:
        print("pip install 'psycopg[binary]'", file=sys.stderr)
        return 2

    total = 0
    with psycopg.connect(args.dsn) as conn:
        for f in files:
            rows = json.loads(f.read_text(encoding="utf-8"))
            if not rows:
                print(f"  {f.stem:32} empty, skipped")
                continue
            keys = list(rows[0])
            if len({r["row_key"] for r in rows}) != len(rows):
                print(f"  {f.stem}: duplicate row_key, refusing to load",
                      file=sys.stderr)
                return 1
            cols = ", ".join(f'"{k}"' for k in keys)
            marks = ", ".join(["%s"] * len(keys))
            updates = ", ".join(f'"{k}" = EXCLUDED."{k}"'
                                for k in keys if k != "row_key")
            sql = (f'INSERT INTO {f.stem} ({cols}) VALUES ({marks}) '
                   f"ON CONFLICT (row_key) DO UPDATE SET {updates}")
            with conn.cursor() as cur:
                cur.executemany(sql, [[r[k] for k in keys] for r in rows])
            conn.commit()
            total += len(rows)
            print(f"  {f.stem:32} {len(rows):>6,} rows")
    print(f"\n  {len(files)} tables, {total:,} rows loaded")
    return 0



if __name__ == "__main__":
    raise SystemExit(main())
